### PR TITLE
TomoPy 0.1.13

### PR DESCRIPTION
**Pull request by dgursoy**
New features
-----------------
- Rotation finding functions: 
    - ```find_center_pc``` (Phase correlation based), 
    - ```find_center_vo``` (FFT based)
- Ring removal functions: 
    - ```remove_ring``` (Applied after image reconstruction), 
    - ```remove_stripe_sf```(From TomoRecon package of M. Rivers)
- Normalization from a series of flat fields: 
    - ```normalize_nf```
- Docker image available at ```dgursoy/tomopy``` for Windows users.

Contributors
-----------------
- Luis Barroso-Luque (Advanced Light Source)
- Nghia Vo (Diamond Light Source)

### CODE REVIEW

**Comment by decarlof** [comment]
@dgursoy I 'conda' installed v 0.1.13 on txmtwo but Vincent is reporting remove_stripe_sf is not found. Was the conda version built against the current github master?

**Comment by dgursoy** [comment]
There are some serious linking problems at txmtwo that has to be resolved locally. I just checked:
```
txmtwo% python -c "import tomopy; print tomopy.__version__"
0.1.11
```

**Comment by decarlof** [comment]
@dgursoy ok let me look into it, f

**Comment by prjemian** [comment]
I'm investigating ...  suspicious of the installation having some problem

**Comment by prjemian** [comment]
Aha! Something does not look right. I'm suspecting that the "conda update tomopy" from last night about 10:15 pm did not complete properly. Or the conda recipe was incorrect.

Follow from here::
```
cd /local/usr32idc/Anaconda/pkgs
ll | grep -i tomopy

drwxr-xr-x 4 usr32idc pfs 4096 Oct 30 10:20 tomopy-0.1.11-nppy27_1
-rw-r--r-- 1 usr32idc pfs 5212068 Oct 30 10:19 tomopy-0.1.11-nppy27_1.tar.bz2
drwxr-xr-x 4 usr32idc pfs 4096 Dec 4 15:29 tomopy-0.1.12-py27_0
-rw-r--r-- 1 usr32idc pfs 5224993 Dec 4 15:28 tomopy-0.1.12-py27_0.tar.bz2
drwxr-xr-x 4 usr32idc pfs 4096 Dec 15 22:16 tomopy-0.1.13-py27_0
-rw-r--r-- 1 usr32idc pfs 5233344 Dec 15 22:16 tomopy-0.1.13-py27_0.tar.bz2

cd tomopy-0.1.13-py27_0
ll

drwxr-xr-x 3 usr32idc pfs 4096 Dec 15 22:16 info
drwxr-xr-x 3 usr32idc pfs 4096 Dec 15 22:16 lib

cd info
ll

-rw-r--r-- 1 usr32idc pfs 6005 Dec 15 15:18 files
-rw-r--r-- 1 usr32idc pfs 310 Dec 15 15:18 git
-rw-r--r-- 1 usr32idc pfs 398 Dec 15 15:18 index.json
drwxr-xr-x 6 usr32idc pfs 4096 Dec 15 22:16 recipe
-rw-r--r-- 1 usr32idc pfs 1516 Dec 15 15:18 recipe.json
```
This is the conda recipe configuration. I see problem(s) in the "files" file:
```
cat files

lib/python2.7/site-packages/lib/libtomopy.so
lib/python2.7/site-packages/test/__init__.py
lib/python2.7/site-packages/test/__init__.pyc
lib/python2.7/site-packages/test/test_io/__init__.py
lib/python2.7/site-packages/test/test_io/__init__.pyc
lib/python2.7/site-packages/test/test_io/test_exchange.py
lib/python2.7/site-packages/test/test_io/test_exchange.pyc
lib/python2.7/site-packages/test/test_io/test_phantom.py
lib/python2.7/site-packages/test/test_io/test_phantom.pyc
lib/python2.7/site-packages/test/test_io/test_reader.py
lib/python2.7/site-packages/test/test_io/test_reader.pyc
lib/python2.7/site-packages/test/test_io/test_writer.py
lib/python2.7/site-packages/test/test_io/test_writer.pyc
lib/python2.7/site-packages/test/test_misc/__init__.py
lib/python2.7/site-packages/test/test_misc/__init__.pyc
lib/python2.7/site-packages/test/test_misc/test_corr.py
lib/python2.7/site-packages/test/test_misc/test_corr.pyc
lib/python2.7/site-packages/test/test_misc/test_morph.py
lib/python2.7/site-packages/test/test_misc/test_morph.pyc
lib/python2.7/site-packages/test/test_prep/__init__.py
lib/python2.7/site-packages/test/test_prep/__init__.pyc
lib/python2.7/site-packages/test/test_prep/test_normalize.py
lib/python2.7/site-packages/test/test_prep/test_normalize.pyc
lib/python2.7/site-packages/test/test_prep/test_phase.py
lib/python2.7/site-packages/test/test_prep/test_phase.pyc
lib/python2.7/site-packages/test/test_prep/test_stripe.py
lib/python2.7/site-packages/test/test_prep/test_stripe.pyc
lib/python2.7/site-packages/test/test_recon/__init__.py
lib/python2.7/site-packages/test/test_recon/__init__.pyc
lib/python2.7/site-packages/test/test_recon/test_algorithm.py
lib/python2.7/site-packages/test/test_recon/test_algorithm.pyc
lib/python2.7/site-packages/test/test_recon/test_rotation.py
lib/python2.7/site-packages/test/test_recon/test_rotation.pyc
lib/python2.7/site-packages/test/test_sim/__init__.py
lib/python2.7/site-packages/test/test_sim/__init__.pyc
lib/python2.7/site-packages/test/test_sim/test_project.py
lib/python2.7/site-packages/test/test_sim/test_project.pyc
lib/python2.7/site-packages/test/test_sim/test_propagate.py
lib/python2.7/site-packages/test/test_sim/test_propagate.pyc
lib/python2.7/site-packages/test/test_util/__init__.py
lib/python2.7/site-packages/test/test_util/__init__.pyc
lib/python2.7/site-packages/test/test_util/test_mproc.py
lib/python2.7/site-packages/test/test_util/test_mproc.pyc
lib/python2.7/site-packages/test/util.py
lib/python2.7/site-packages/test/util.pyc
lib/python2.7/site-packages/tomopy-0.1.12-py2.7-linux-x86_64.egg-info/PKG-INFO
lib/python2.7/site-packages/tomopy-0.1.12-py2.7-linux-x86_64.egg-info/SOURCES.txt
lib/python2.7/site-packages/tomopy-0.1.12-py2.7-linux-x86_64.egg-info/dependency_links.txt
lib/python2.7/site-packages/tomopy-0.1.12-py2.7-linux-x86_64.egg-info/native_libs.txt
lib/python2.7/site-packages/tomopy-0.1.12-py2.7-linux-x86_64.egg-info/not-zip-safe
lib/python2.7/site-packages/tomopy-0.1.12-py2.7-linux-x86_64.egg-info/top_level.txt
lib/python2.7/site-packages/tomopy/__init__.py
lib/python2.7/site-packages/tomopy/__init__.pyc
lib/python2.7/site-packages/tomopy/data/baboon.tif
lib/python2.7/site-packages/tomopy/data/barbara.tif
lib/python2.7/site-packages/tomopy/data/cameraman.tif
lib/python2.7/site-packages/tomopy/data/checkerboard.tif
lib/python2.7/site-packages/tomopy/data/lena.tif
lib/python2.7/site-packages/tomopy/data/peppers.tif
lib/python2.7/site-packages/tomopy/data/shepp2d.tif
lib/python2.7/site-packages/tomopy/data/tooth.h5
lib/python2.7/site-packages/tomopy/io/__init__.py
lib/python2.7/site-packages/tomopy/io/__init__.pyc
lib/python2.7/site-packages/tomopy/io/exchange.py
lib/python2.7/site-packages/tomopy/io/exchange.pyc
lib/python2.7/site-packages/tomopy/io/phantom.py
lib/python2.7/site-packages/tomopy/io/phantom.pyc
lib/python2.7/site-packages/tomopy/io/reader.py
lib/python2.7/site-packages/tomopy/io/reader.pyc
lib/python2.7/site-packages/tomopy/io/writer.py
lib/python2.7/site-packages/tomopy/io/writer.pyc
lib/python2.7/site-packages/tomopy/misc/__init__.py
lib/python2.7/site-packages/tomopy/misc/__init__.pyc
lib/python2.7/site-packages/tomopy/misc/corr.py
lib/python2.7/site-packages/tomopy/misc/corr.pyc
lib/python2.7/site-packages/tomopy/misc/morph.py
lib/python2.7/site-packages/tomopy/misc/morph.pyc
lib/python2.7/site-packages/tomopy/prep/__init__.py
lib/python2.7/site-packages/tomopy/prep/__init__.pyc
lib/python2.7/site-packages/tomopy/prep/normalize.py
lib/python2.7/site-packages/tomopy/prep/normalize.pyc
lib/python2.7/site-packages/tomopy/prep/phase.py
lib/python2.7/site-packages/tomopy/prep/phase.pyc
lib/python2.7/site-packages/tomopy/prep/stripe.py
lib/python2.7/site-packages/tomopy/prep/stripe.pyc
lib/python2.7/site-packages/tomopy/recon/__init__.py
lib/python2.7/site-packages/tomopy/recon/__init__.pyc
lib/python2.7/site-packages/tomopy/recon/acceleration.py
lib/python2.7/site-packages/tomopy/recon/acceleration.pyc
lib/python2.7/site-packages/tomopy/recon/algorithm.py
lib/python2.7/site-packages/tomopy/recon/algorithm.pyc
lib/python2.7/site-packages/tomopy/recon/rotation.py
lib/python2.7/site-packages/tomopy/recon/rotation.pyc
lib/python2.7/site-packages/tomopy/recon/wrappers.py
lib/python2.7/site-packages/tomopy/recon/wrappers.pyc
lib/python2.7/site-packages/tomopy/sim/__init__.py
lib/python2.7/site-packages/tomopy/sim/__init__.pyc
lib/python2.7/site-packages/tomopy/sim/project.py
lib/python2.7/site-packages/tomopy/sim/project.pyc
lib/python2.7/site-packages/tomopy/sim/propagate.py
lib/python2.7/site-packages/tomopy/sim/propagate.pyc
lib/python2.7/site-packages/tomopy/util/__init__.py
lib/python2.7/site-packages/tomopy/util/__init__.pyc
lib/python2.7/site-packages/tomopy/util/dtype.py
lib/python2.7/site-packages/tomopy/util/dtype.pyc
lib/python2.7/site-packages/tomopy/util/extern.py
lib/python2.7/site-packages/tomopy/util/extern.pyc
lib/python2.7/site-packages/tomopy/util/mproc.py
lib/python2.7/site-packages/tomopy/util/mproc.pyc
```

First item that jumps out at me are the entries like this one:
```
lib/python2.7/site-packages/tomopy-0.1.12-py2.7-linux-x86_64.egg-info/PKG-INFO
```

Why is this recipe referencing anything from version 0.1.12?

Another question, not likely related to the original version info question, is triggered by installation on these paths::
```
lib/python2.7/site-packages/lib/
lib/python2.7/site-packages/test/
```
Why aren't those installed under a tomopy subdirectory?
They look vulnerable to destruction by installation of some other package that just happens to install under those paths. Low risk of that for::
```
lib/python2.7/site-packages/lib/libtomopy.so
```
Pretty good risk of getting at least these files overwritten by installing a different package that creates a "test" subdirectory::
```
lib/python2.7/site-packages/test/__init__.py
lib/python2.7/site-packages/test/__init__.pyc
lib/python2.7/site-packages/test/utils.py
lib/python2.7/site-packages/test/utils.pyc
```
At this point, before doing a "wipe clean and reinstall from scratch", my recommendation is to remove the compressed package file and pre-installation directory for the 0.1.13 version, then attempt a conda update tomopy again and observe carefully the result. Perhaps the conda recipe should be checked first to ensure it is OK.
```
/local/usr32idc/Anaconda/bin/conda list | grep -i tomopy
# verify this reports the 0.1.13 version
cd /local/usr32idc/Anaconda/pkgs
/bin/rm -rf tomopy-0.1.13-py27_0*
/local/usr32idc/Anaconda/bin/conda list | grep -i tomopy
# verify this does NOT report the 0.1.13 version
/local/usr32idc/Anaconda/bin/conda update tomopy
# verify that any version numbers in path names refer to 0.1.13
```

**Comment by prjemian** [comment]
Looks like we should open a new issue for this, rather than piggybacking an already merged issue.

**Comment by tomopy** [comment]
Below is the install output from last night (I saved it when I realized something did not work), all looked fine:

f

txmtwo% conda install -c dgursoy tomopy
Fetching package metadata: ........
Solving package specifications: .....................
Package plan for installation in environment /local/usr32idc/Anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    fftw-3.3.4                 |                0         3.7 MB  dgursoy
    conda-env-2.4.5            |           py27_0          24 KB  defaults
    numpy-1.10.2               |           py27_0         5.9 MB  defaults
    requests-2.9.0             |           py27_0         604 KB  defaults
    setuptools-18.8.1          |           py27_0         345 KB  defaults
    conda-3.18.9               |           py27_0         176 KB  defaults
    cycler-0.9.0               |           py27_0           6 KB  defaults
    edffile-1.6                |           py27_0          35 KB  dgursoy
    h5py-2.5.0                 |      np110py27_4         2.4 MB  defaults
    netcdf4-1.1.9              |      np110py27_0         1.3 MB  defaults
    pyfftw-0.9.2               |           py27_0         180 KB  dgursoy
    pywavelets-0.3.0           |           py27_0         805 KB  dgursoy
    scipy-0.16.1               |      np110py27_0        23.9 MB  defaults
    spefile-1.6                |           py27_0          12 KB  dgursoy
    tifffile-2014.08.24        |           py27_0         179 KB  dgursoy
    matplotlib-1.5.0           |      np110py27_0         8.2 MB  defaults
    scikit-image-0.11.3        |      np110py27_0        24.0 MB  defaults
    tomopy-0.1.13              |           py27_0         5.0 MB  dgursoy
    ------------------------------------------------------------
                                           Total:        76.7 MB

The following NEW packages will be INSTALLED:

    cycler:       0.9.0-py27_0       defaults
    fftw:         3.3.4-0            dgursoy
    pyfftw:       0.9.2-py27_0       dgursoy

The following packages will be UPDATED:

    conda:        3.18.8-py27_0         defaults  --> 3.18.9-py27_0      defaults
    conda-env:    2.4.4-py27_0          defaults  --> 2.4.5-py27_0       defaults
    edffile:      1.6-np19py27_0        <unknown> --> 1.6-py27_0         dgursoy
    h5py:         2.5.0-np19py27_3      defaults  --> 2.5.0-np110py27_4  defaults
    matplotlib:   1.4.3-np19py27_2      defaults  --> 1.5.0-np110py27_0  defaults
    netcdf4:      1.1.9-np19py27_0      defaults  --> 1.1.9-np110py27_0  defaults
    numpy:        1.9.3-py27_0          defaults  --> 1.10.2-py27_0      defaults
    pywavelets:   0.2.2-np19py27_0      dgursoy   --> 0.3.0-py27_0       dgursoy
    requests:     2.8.1-py27_0          defaults  --> 2.9.0-py27_0       defaults
    scikit-image: 0.11.3-np19py27_0     defaults  --> 0.11.3-np110py27_0 defaults
    scipy:        0.16.0-np19py27_1     defaults  --> 0.16.1-np110py27_0 defaults
    setuptools:   18.5-py27_0           defaults  --> 18.8.1-py27_0      defaults
    spefile:      1.6-np19py27_0        <unknown> --> 1.6-py27_0         dgursoy
    tifffile:     2014.08.24-np19py27_0 <unknown> --> 2014.08.24-py27_0  dgursoy
    tomopy:       0.1.12-py27_0         dgursoy   --> 0.1.13-py27_0      dgursoy

Proceed ([y]/n)? y

Fetching packages ...
fftw-3.3.4-0.t 100% |################################################################| Time: 0:00:00   8.19 MB/s
conda-env-2.4. 100% |################################################################| Time: 0:00:00   1.25 MB/s
numpy-1.10.2-p 100% |################################################################| Time: 0:00:03   1.60 MB/s
requests-2.9.0 100% |################################################################| Time: 0:00:00   1.55 MB/s
setuptools-18. 100% |################################################################| Time: 0:00:00   1.46 MB/s
conda-3.18.9-p 100% |################################################################| Time: 0:00:00   1.35 MB/s
cycler-0.9.0-p 100% |################################################################| Time: 0:00:00   4.14 MB/s
edffile-1.6-py 100% |################################################################| Time: 0:00:00 874.85 kB/s
h5py-2.5.0-np1 100% |################################################################| Time: 0:00:01   1.57 MB/s
netcdf4-1.1.9- 100% |################################################################| Time: 0:00:00   1.53 MB/s
pyfftw-0.9.2-p 100% |################################################################| Time: 0:00:00   1.58 MB/s
pywavelets-0.3 100% |################################################################| Time: 0:00:00   3.01 MB/s
scipy-0.16.1-n 100% |################################################################| Time: 0:00:14   1.74 MB/s
spefile-1.6-py 100% |################################################################| Time: 0:00:00   7.46 MB/s
tifffile-2014. 100% |################################################################| Time: 0:00:00   1.88 MB/s
matplotlib-1.5 100% |################################################################| Time: 0:00:05   1.55 MB/s
scikit-image-0 100% |################################################################| Time: 0:00:16   1.53 MB/s
tomopy-0.1.13- 100% |################################################################| Time: 0:00:00   9.48 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################################################| 100%

________________________________

**Comment by prjemian** [comment]
Too bad that the details did not show up in this summary report.

**Comment by tomopy** [comment]
ok I uninstalled, clone the repository and did a python setup.py install and I am now on the correct version (0.1.13)

Is it possible that something went worg in the binstar upload?

f

________________________________

**Comment by prjemian** [comment]
An error in the files uploaded to binstar is plausible.  I did not see an opportunity in the Python packaging to make this same version number error.

**Pull request merged**
