### PR TITLE
Add CheckAtomic package helper to fix build on riscv64 architecture (…

### PR DESCRIPTION
**Pull request by LocutusOfBorg**
…needing latomic library)

### CODE REVIEW

**Comment by carterbox** [comment]
Atomic operations are only needed for the CUDA accelerated functions. AFAIK, CUDA doesn't support riscv64 hosts, so correctly linking to libatomic for riscv64 is not needed.

You should be able to compile for riscv64 without CUDA/libatomic by setting the CMake Variable `TOMOPY_USE_CUDA:BOOL=OFF`. If the compiler still complains that the atomic header is missing, then that is because we have a header which should be patched not because you need libatomic.

**Comment by LocutusOfBorg** [comment]
@carterbox cuda is disabled
https://launchpadlibrarian.net/648979493/buildlog_ubuntu-lunar-riscv64.tomopy_1.10.4+ds1-7_BUILDING.txt.gz
```
/usr/bin/ld: libptl.a(UserTaskQueue.cc.o): in function `void std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&)':
/usr/include/c++/12/mutex:859: undefined reference to `__atomic_compare_exchange_1'
/usr/bin/ld: libptl.a(UserTaskQueue.cc.o): in function `std::deque<VTask*, std::allocator<VTask*> >::pop_front()':
/usr/include/c++/12/bits/stl_deque.h:1578: undefined reference to `__atomic_compare_exchange_1'
/usr/bin/ld: libptl.a(UserTaskQueue.cc.o): in function `std::__atomic_base<bool>::load(std::memory_order) const':
/usr/include/c++/12/bits/atomic_base.h:488: undefined reference to `__atomic_compare_exchange_1'
/usr/bin/ld: libptl.a(UserTaskQueue.cc.o): in function `UserTaskQueue::GetThreadBin() const':
/usr/src/tomopy-1.10.4+ds1-7/source/PTL/source/UserTaskQueue.cc:129: undefined reference to `__atomic_compare_exchange_1'
/usr/bin/ld: libptl.a(UserTaskQueue.cc.o): in function `void std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&)':
/usr/include/c++/12/mutex:851: undefined reference to `__atomic_compare_exchange_1'
/usr/bin/ld: libptl.a(UserTaskQueue.cc.o):/usr/include/c++/12/ext/atomicity.h:85: more undefined references to `__atomic_compare_exchange_1' follow
/usr/bin/ld: source/libtomo/accel/CMakeFiles/libtomopy-accel.dir/cxx/common.cc.o: in function `std::__atomic_base<short>::operator++()':
/usr/include/c++/12/bits/atomic_base.h:385: undefined reference to `__atomic_fetch_add_2'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/skbuild/setuptools_wrap.py", line 640, in setup
    cmkr.make(make_args, install_target=cmake_install_target, env=env)
  File "/usr/lib/python3/dist-packages/skbuild/cmaker.py", line 684, in make
    self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
  File "/usr/lib/python3/dist-packages/skbuild/cmaker.py", line 715, in make_impl
    raise SKBuildError(

An error occurred while building with CMake.
  Command:
    cmake --build . --target install --config Release --
  Install target:
    install
  Source directory:
    /<<PKGBUILDDIR>>
  Working directory:
    /<<PKGBUILDDIR>>/_skbuild/linux-riscv64-3.11/cmake-build
```

**Comment by LocutusOfBorg** [comment]
I'm now trying to only patch PTL repo, and not main tomopy

**Comment by LocutusOfBorg** [comment]
Yes, I made a mistake in PTL variable name, not in tomopy

**Comment by LocutusOfBorg** [comment]
we need PTL to sync with https://github.com/jrmadsen/PTL/pull/41

**Comment by carterbox** [comment]
You can also disable PTL with `TOMOPY_USE_PTL:BOOL=OFF`

**Comment by carterbox** [comment]
It looks like [<atomic> is still *included* with the PTL headers](https://github.com/tomopy/tomopy/blob/4d2afe217d4e35dfc72313ec3fe803a5dbab60c1/source/libtomo/accel/macros.hh#L102) even if TOMOPY_USE_PTL is set to OFF. However, I'm still pretty confident that atomics aren't *used* unless CUDA is also enabled.

**Comment by LocutusOfBorg** [comment]
@carterbox I did patch *that branch* :)

**Comment by LocutusOfBorg** [comment]
[21036](https://github.com/jrmadsen/PTL/pull/41)

**Comment by LocutusOfBorg** [comment]
so if you update (once the PR is merged) the submodule to the latest tomopy branch commit id (e.g. b39f82fd91db6c6955ab172b4ba95add38ece7ae) we will get the fix

**Comment by LocutusOfBorg** [comment]
one partial fix already is in that branch
https://github.com/jrmadsen/PTL/commits/tomopy

**Comment by carterbox** [comment]
I have no way of testing builds on RISV, but I assume you do. Please reopen this PR and include whatever changes to TomoPy + the updated submodule whenever you've got something working.

**Pull request closed without merging**
