### PR TITLE
ASTRA wrapper fixes

### PR DESCRIPTION
**Pull request by dmpelt**
Fix for running ASTRA CPU algorithms that require extra options. This error was caused by my changes in #217 .

### CODE REVIEW

**Comment by dmpelt** [comment]
PS. No idea why travis fails with 3.4. It seems to be a conda/travis problem, since the current master fails for me at this time too. The #229 build did not fail, so something in conda/travis changed today apparently.

**Comment by dgursoy** [comment]
Not sure we want that, but would adding ```--copy``` flag to conda may solve it? It will then install all packages using copies instead of hard- or soft-linking.

But if could also be a bug in Travis since I didn't understand why it downgrades from Python 3.5.2 to Python 3.4.5-0 (and at the beginning it said it has Python 3.4.2).

**Comment by dgursoy** [comment]
@dmpelt what is the status of this PR?

**Comment by dmpelt** [comment]
I think it is actually working, but Travis was having some problems that day. Is there a way to force a Travis rebuild without pushing some random commit to it?

**Comment by dgursoy** [comment]
Restarted builds. Only 3.4 was failing.

**Comment by dgursoy** [comment]
Seems good to go!

**Pull request merged**
