### PR TITLE
Fixed up chunking and multithreading.

### PR DESCRIPTION
**Pull request by michael-sutherland**
Fixed a bug where recon wasn't using the nchunk parameter (see #221 ), it now does chunking in a better way.  Also, cleaned up the extern module to always call the underlying function instead of sometimes returning a tuple containing the function and its parameters.  Further, fixed up the Astra wrapper to match my changes.  @dmpelt The astra wrapper doesn't appear to be supporting multiple GPUs, but I think this was already an issue.  Specifically, if I try to run on two GPUs and step through the code, the first one starts up and then is stopped when I submit the thread for the second one.

### CODE REVIEW

**Comment by kyueaes** [comment]
What is the output command of this "nvidia-smi -s", Michael?

Regards,
Ke Yue
________________________________

**Comment by michael-sutherland** [comment]
I am running two Titan X (Pascal) GPUs.  Did you mean "nvidia-smi -a"?

**Comment by kyueaes** [comment]
Hi Michael:

No, how about "nvidia-smi -q", what is the ouput? 

I guess it might because your gpu is not set to exclusive mode.

Regards,
Ke Yue

________________________________________

**Comment by michael-sutherland** [comment]
I set to exclusive mode, but am seeing the same issue.  Here's the output from nvidia-smi -q.

[gpu_query.txt](https://github.com/tomopy/tomopy/files/628294/gpu_query.txt)

**Comment by kyueaes** [comment]
umm...it might be some other issue then. If possible could you try set it to  DEFAULT and EXCLUSIVE_THREAD MODE to check if it is working?

Thanks,

**Comment by michael-sutherland** [comment]
I had it on DEFAULT originally.  It won't let me set EXCLUSIVE_THREAD, it has apparently been depricated.

**Comment by michael-sutherland** [comment]
If someone can verify that it works for them with 2 GPUs, I'll update my commit comment.  For now, moving the discussion to #242.

**Comment by michael-sutherland** [comment]
Just fixed a bug in the poll request for when you specify nchunk (it was creating too many slices).

**Comment by dgursoy** [comment]
@michael-sutherland Should this thread be kept open or ready to go?

**Comment by michael-sutherland** [comment]
It should be ready to go.

**Comment by dgursoy** [comment]
All right then. Thanks!

**Pull request merged**
