### PR TITLE
Build with CUDA toolkit on Travis

### PR DESCRIPTION
**Pull request by carterbox**
This purpose of this pull is to add the CUDA toolkit to our build infrastructure so that we can catch CUDA compiling errors earlier.

### CODE REVIEW

**Comment by dgursoy** [comment]
Is this still on progress? Any explanation about why the tests are failing?

**Comment by carterbox** [comment]
To be clear, merging #404 does not depend on this pull. This pull is something that Jonathan and I had discussed briefly just as an additional sanity check. This pull would catch *compiling errors only* because we do not have a CI with a CUDA GPU set up anywhere.

The current problem that I'm having is that CMake isn't recognizing that the CUDA compiler is installed. It's supposed to check the environment for `CUDA_TOOLKIT_ROOT_DIR`, but it seems to decide that CUDA is not installed even though this file path exists. I suspect one of the following outcomes:

1. I'm not passing this variable to CMake correctly
2. The goals of this pull cannot be accomplished because CMake requires the CUDA drivers be installed, but the CUDA installed will not install drivers without detecting CUDA hardware (which doesn't exist on Travis).

**Comment by carterbox** [comment]
anaconda.org is down. Try again later.

**Comment by carterbox** [comment]
Build is failing with the following message:
```
CMake Error at /home/travis/miniconda/envs/tomopy/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CUDA (missing: CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS
  CUDA_CUDART_LIBRARY)
```
However, I have passed all of those variables to CMake, so I don't know why it is unhappy. I will need to do some testing locally on a machine sans CUDA GPU.

**Comment by carterbox** [comment]
I think the problem is that CMake doesn't pass the host compiler to `nvcc` when it is testing for a working CUDA compiler, so the search will fail. `nvcc` only searches for `gcc` in the usual locations, and it doesn't take environment variables like `$CC`. I was able to get the CUDA modules to compile with the conda-forge compiler by putting a symbolic link at `/usr/local/bin/gcc`.

**Comment by carterbox** [comment]
One thing to think about is that `1.5.x` has increased Travis build times from ~8 min to ~23 min. Not sure if that's a big deal or not.

**Comment by jrmadsen** [comment]
Compiling more code and building it twice so that's to be expected. Although you don't need the second build since the coverage is CDash got broken.

**Comment by carterbox** [comment]
Now the build time is a problem. Our build times are capped at 50 minutes and the tests are exceeding this allotted time. I'm going separating them into shorter separate builds using the build matrix.

**Comment by jrmadsen** [comment]
Add `--phantom-size 128` like the one in the above. The pyctest script when "coverage" was enabled skipped the built-in phantoms because C/C++ code coverage requires you to compile with zero optimizations so it tends to be very slow. When you removed, the coverage flag, it started reconstructing the built-in phantoms and the default size is 512 pix images.

**Comment by carterbox** [comment]
Thanks for explaining the increased build times. However, I've broken the builds into shorter builds anyways due to the fact that these changes to the C extension shouldn't be affected by the python version. Thus, it's not necessary to build with CUDA or tasking on all of the python versions? Here's the new build matrix:

| python | CUDA | tasking |
| - | - |-|
| 2.7 | False | True |
| 3.6 | False | False |
| 3.6 | False | True |
| 3.7 | False | True |
| 3.7 | True | True |

**Comment by carterbox** [comment]
We're also testing *all* of the 2D phantoms on Travis. Can I cut that back to just one?

**Comment by jrmadsen** [comment]
Build matrix looks fine to me. If you want to scale back the number of phantoms being tested, go for it.

**Comment by jrmadsen** [comment]
Maybe only scale it back to three though. In the event you start seeing weird results somewhere, having 3 tests for each algorithm is the minimum you would need to diagnose whether something is widespread or isolated

**Comment by jrmadsen** [comment]
It looks fine. You can get rid of the TOMOPY_USE_C_ALGORITHMS environment variable. Also, you might have had issues with the conda-forge CUDA bc it wants a clang 6 compiler. I tested it the other day on my Mac. You might want to try adding the LLVM toolchain repo and installing clang via apt-get. I suspect the it's not doing that bc you are installing GCC via conda. Clang tends to produce slower code than GCC so definitely don't make a switch in the env files though,

**Comment by carterbox** [comment]
I'm not using the conda-forge `cudatoolkit-dev` package because it doesn't actually provide the toolkit, it just wraps the installer from NVidia. I'm not sure why they chose to do that, but I found it annoying. I'll remove that `TOMOPY_USE_C` variable in the future.

In terms of building with CUDA for distribution, there is a container with the full cudatoolkit preinstalled [somewhere in development for the conda-forge infrastructure](https://github.com/conda-forge/docker-images/pull/93#issuecomment-497183733). I'm think I'm going to wai for that to arrive because installing the cudatoolkit to the build environment myself is super annoying.

**Pull request merged**
