### PR TITLE
Add Total Variation reconstruction method and Gradient descent method

### PR DESCRIPTION
**Pull request by math-vrn**
Main differences
1) tv.c file was written according to the syntax of other sources for the iterative reconstruction like mlem.c, art.c, etc.
2) reference to the tv method was added in doc/souce/bibtex/refs.bib file
3) tv.npy file was added for performing unit tests
4) grad.c file was written according to the syntax of other sources for the iterative reconstruction like mlem.c, art.c, etc.
5) grad.npy file was added for performing unit tests

### CODE REVIEW

**Comment by dgursoy** [comment]
@carterbox This is somehow linked to #333. Should we merge this and fix the notation in #333?

**Comment by dgursoy** [comment]
Thanks!

**Comment by carterbox** [comment]
Because of #335, the commit hashes for the main branch have changed, you will need to cherry-pick the commits from this pull onto the new tomopy/master.

**Comment by dgursoy** [comment]
See #336

**Pull request closed without merging**
