### PR TITLE
BUG: Fix broken setup.py develop with build system update

### PR DESCRIPTION
**Pull request by carterbox**
The new build system (#355) broke setup.py develop. Fix provided by
@jrmadsen prevents Make from complaining when it is asked to
install the shared library to the same directory twice.

### CODE REVIEW

**Comment by jrmadsen** [comment]
Also replace this:
```python
def clean_libtomopy():
    """Clean libtomopy shared library for the current system."""
    subprocess.check_call(('make', 'clean', '-f', get_makefile()))
```
with this:
```python
def clean_libtomopy():
    """Clean libtomopy shared library for the current system."""
    if os.path.exists("Mk.config"):
        subprocess.check_call(('make', 'clean', '-f', get_makefile()))
    else:
        print("Mk.config does not exist. Assuming nothing to clean...")
```
It wasn't causing an failures but PyCTest logs were polluted

**Comment by carterbox** [comment]
@jrmadsen Do you want that "Mk.config does not exist. Assuming nothing to clean..." to go to `stderr` instead? `print` goes to `stdout`.

**Comment by jrmadsen** [comment]
No its not an error really, PyCTest just calls clean by default whenever it starts up to make sure TomoPy is actually doing a fresh build and doesn't report zero build warnings, etc. because nothing actually got recompiled.

**Comment by jrmadsen** [comment]
@dgursoy @carterbox can we get this PR closed? I've got some optimizations that depend on OpenMP SIMD instructions and thus require new build flags. The optimizations are producing around 1.2x to 1.25x speed up for all the iterative algorithms on all the architectures at NERSC (and I expect workstations will see the same degree of speed-up)

**Comment by dgursoy** [comment]
Docs is broken after this merge.

**Comment by dgursoy** [comment]
Docs is fine. It was a RTD issue.

**Pull request merged**
