### PR TITLE
Bug fixes for windows

### PR DESCRIPTION
**Pull request by EricPythonMaster**
This PR primarily introduces a number of fixes for compiling and running on Windows.
Also, when the number of slices is less than the number of cores, do not create extra work for the unused cores.

### CODE REVIEW

**Comment by EricPythonMaster** [comment]
For those who follow this, the error that causes the tests to fail are not reproducible on windows, however, the bug with multi-threading still occurs through FFTW.

Somewhere along the way, fftw receives a nullptr and it causes it to crash.
I also tried to use the "fftw_make_planner_thread_safe" and it didn't resolve anything. This was tested on fftw 3.3.5 (it is known that in 3.3.5 the thread safe doesn't work) and there are no ffftw 3.3.6 binaries yet for windows.  I will have to compile it at some point, but this could be it looking at the gridrec code. If someone wants to build them and send them to me, that would be greatly appreciated.

It would be surprising if it was just that as it works fine on linux.
If there are bugs on linux, but  they aren't apparent, or no one has noticed them yet.
I will definitely keep working on this when I have some time.

**Comment by EricPythonMaster** [comment]
For anyone wondering:
FFTW3.3.6 on windows 
https://anaconda.org/ccpi/fftw

**Comment by EricPythonMaster** [comment]
I used a mutex in grid rec. That works now.
Multiprocessing also works now.

For some reason, project is not working.
Doing a projection creates a 0 valued matrix.

**Comment by EricPythonMaster** [comment]
@dgursoy @dmpelt 
Alright, all of the test have passed now with minimal impacts on the rest of the code.
The biggest change is with fftw in gridrec. I've now wrapped it with a mutex. It was a problem for winidows, but apparently no obvious problems on linux. However, to prevent possible issues, I left the mutex for linux as well.

The multiprocessing on windows works as well. Here's a screenshot of the test passing on my windows machine.
windows test passed

The main issue with the multiprocessing was that it was not used properly. The numpy arrays were getting pickled between processes on windows. With this PR,I 've also noticed that the multiprocessing tests run faster, at least on windows.

**Comment by dgursoy** [comment]
@EricPythonMaster I wonder if everything is fine in Windows after the current replacement of FFTW with mkl_fft. How easy one can write a AppVeyor CI script for Win?

**Comment by thejinx0r** [comment]
@dgursoy 
This is my regular account. 

I have no experience with AppVeyor.
I'll have to look in to it more carefully, but a glance, the syntax is quite similar to Travis.

I think it would be quite easy to write something up for it.

**Comment by dgursoy** [comment]
@thejinx0r I have no experience with Windows, and no way to test. I hope somebody can jump in and give it a try.

**Comment by thejinx0r** [comment]
@dgursoy 
I'll give it a go.
Definitely something I wanted to add to the CI. I just never knew AppVeyor supported Windows.

**Pull request merged**
