### PR TITLE
Fix for running on mulitple GPUs.

### PR DESCRIPTION
**Pull request by michael-sutherland**
There was a shared dict that was being modified with the GPU Index in different threads.  Fix is to deepcopy the dict before passing to different threads.

### CODE REVIEW

**Comment by michael-sutherland** [comment]
This fixes #242.

**Comment by dmpelt** [comment]
Small comment: could we also do the deep copy at the `cfg['option'] = opts['extra_options']` line (i.e. `cfg['option'] = copy.deepcopy(opts['extra_options'])`)? In that case, we are only copying the `extra_options` dict, which is potentially faster than copying the entire `opts` dict (also, does `copy.deepcopy` create a deep copy of a dict within a dict?).

**Comment by michael-sutherland** [comment]
copy.copy() is a shallow copy.  copy.deepcopy() will copy all of the elements recursively.  I debated putting the copy there as well, but decided to put it where the multithreading occurred (since astra_rec_cuda gets called in the multi-threaded and single-threaded case).  I'm not sure which is actually better from a readability and maintainability perspective.

**Comment by michael-sutherland** [comment]
I thought about it last night and am going to change the copy to the place you specified.  We shouldn't be changing the parameters we pass in unless it is explicit and could also mess something up for the single threaded case in the future.  I'll switch where the change is happening and update the pull request.

**Comment by dmpelt** [comment]
I was just about to comment that either way was fine with me :)

The PR looks good to be merged to me!

**Pull request merged**
