### PR TITLE
added filter choice in write_center

### PR DESCRIPTION
**Pull request by decarlof**

### CODE REVIEW

**Comment by decarlof** [comment]
@vdeandrade, @dgursoy this replaces [288](https://github.com/tomopy/tomopy/pull/288).

**Comment by decarlof** [comment]
is failing on the test_rotation but the new added parameters are optional (algorithm='gridrec', filter_name='parzen') so the test call:

        write_center(
            read_file('proj.npy'),
            read_file('angle.npy'),
            dpath, cen_range=cen_range)

should still be OK, no?

**Comment by dgursoy** [comment]
I think default was 'shepp', not 'parzen'. This might be the reason that the test is failing. Maybe this would work?
```
write_center(
        read_file('proj.npy'),
        read_file('angle.npy'),
        dpath, cen_range=cen_range, 
        algorithm='gridrec', filter_name='shepp')
```

**Comment by dgursoy** [comment]
'write_center' test is now passing, but 'find_center' test is failing because it is also sharing the same functions underneath, and needs to be updated as well. Once it is fixed I believe this is ready to go.

**Comment by dgursoy** [comment]
All good to go. Thanks!

**Comment by decarlof** [comment]
@dgursoy wait on @vdeandrade comments before accept it. The old pull request from @vdeandrade had changes besides write_center in  _adjust_hist_limits and _adjust_hist_limits (see original pull request at  [288](https://github.com/tomopy/tomopy/pull/288) for details). These are not needed to add the filter choice in write_center so I removed them. @vdeandrade do you remember what other functionality you wanted to add here?

**Comment by decarlof** [comment]
@dgursoy ops too late ....

**Pull request merged**
