### PR TITLE
1.5.x - GPU support, rotation-based recon, MSVC support

### PR DESCRIPTION
**Pull request by jrmadsen**
- CMake build system to handle addition of code in two new languages: C++ and CUDA
- Python bindings to C++/CUDA code still go through C interface (i.e. no direct binding)
- SIRT and MLEM have been implemented on the GPU and CPU using rotation-based algorithm
    - GPU support has been validated for Windows and Linux
    - CPU version uses OpenCV for rotation
        - OpenCV distributed via conda + MinGW on Windows does not work. Use MSVC compiler on Windows.
    - GPU version uses NPP for rotation
    - benchmarking on NVIDIA P100: ~11x slower than gridrec but vastly improved reconstruction quality
    - benchmarking on NVIDIA V100: per-slice speed-up over ray-based algorithm is ~650x, e.g. a TomoBank reconstruction (2048p + 1,500 proj angles) formerly requiring ~6.5 hours is completed in ~40 seconds
- Support for Microsoft Visual C++ (MSVC) compiler
    - Implemented gridrec in C++ (uses `std::complex`) which is enabled by default on Windows
- To enable new algorithms, include `accelerated=True` to `tomopy.recon` for SIRT and MLEM
    - there are other options available but unless there is an explicitly understanding the effects of the other parameters, use the defaults.
- Multi-GPU support is available
    - Automatic detection of number of available devices
    - Multiple threads started at Python level automatically spread out over the number of available GPUs 
- Secondary thread-pools created in C++ code to provide highly efficient communication with the GPU and additional parallelism on the CPU.
    - When running on the GPU, set `ncore` parameter to `tomopy.recon` to the number of GPUs available. 
    - Each "Python" thread creates a unique secondary thread-pool with a default size of `2 * number-of-cpus`. This is intentional and, in general, the larger the secondary thread-pool, the more efficiently the CPU-GPU communication latency is hidden. However, in general, more than 24 threads per thread-pool provides no benefit (all latency is essentially hidden at that point)

### CODE REVIEW

**Comment by jrmadsen** [comment]
A squash + merge should fix the noise in the commit log. I didn't create this branch so I am not sure how it was originally rebased off of master

**Comment by dgursoy** [comment]
Thanks @jrmadsen! This is a large PR and probably can take one or two weeks to digest. I'll have a quick look first and try to add few more reviewers to speed-up the process. Thanks again.

**Comment by jrmadsen** [comment]
I found a bug in PTL that would (occasionally) cause a segfault when the Python threads exited. The commit notes why this happened but I'll repeat it here:

- Each thread created at the Python level creates its own thread-pool
- The lifetime of the ThreadPool instance per Python thread is handled by a `std::unique_ptr<ThreadPool>` which gets destroyed when `RuntimeOptions` (include/data.hh) is destroyed.
- The threads in the thread-pool hold a mutex owned by the ThreadPool instance for synchronization reasons
- In the event that the `ThreadPool::~ThreadPool` was called _before_ the threads exited `ThreadPool::execute_thread(VUserTaskQueue*)`, the thread's attempt to unlock the mutex created/destroyed by the ThreadPool instance became an undefined operation (unlocking mutex that didn't exist) and would result generally in a seg-fault (but not always because it is an undefined operation).

This has been resolved to the best of my knowledge. I have ran 100+ reconstructions and this behavior no longer seems to be present but in the event an inexplicable seg-fault occurs when returning from `tomopy.recon(..., accelerated=True)`, let me know.

**Comment by jrmadsen** [comment]
@carterbox Can you re-trigger AppVeyor to run on this PR? It looks like it did not run so GitHub is marking it as "failing"

**Comment by carterbox** [comment]
Appveyor refused to run because there was a "conflict" with `master`. I pulled the most recent changes from `master` and now the build is queued. The "conflict" is because we moved the source files into the source folder.

**Comment by carterbox** [comment]
It seems that the Linux builds are failing after I update this branch with recent commits from `master`. I've restarted the builds from before the merge in order to make sure that this isn't caused by `conda-forge`.

**Comment by carterbox** [comment]
The Linux builds are failing with the following error:
```
ERROR: Failure: ImportError (libopenblas.so.0: cannot open shared object file: No such file or directory)
```
Let me check what dependencies have changed between before and now.

**Comment by carterbox** [comment]
I'm going to try and do the build locally to narrow down the problem.

**Comment by jrmadsen** [comment]
I am 99.9% certain you will find the issue lies with OpenCV + numpy. I would bet their feedstocks got updated and the new "Solving environment" resulted in a decision that downloading the openblas compiled versions, e.g.

Locally, I have the following OpenCV:
> opencv                    3.4.2            py36h6fd60c2_1
> numpy                     1.16.2           py36h8b7e671_1    conda-forge

but this exists:

> opencv                         4.0.1 py36_blas_openblash26fe798_200  conda-forge         
> numpy                         1.15.4 py36_blas_openblashb06ca3d_0  conda-forge

This is why I had previously specified a OpenCV version in the envs files. It protected against this issue but I am guessing it no longer does. The OpenCV/CPU versions are very useful when a GPU is not available and thus the accelerated NPP/GPU algorithms cannot be tested/run but we probably need to find a way to specify to conda to not find a "openblas" solution.

**Comment by jrmadsen** [comment]
Correction: the root of the issue probably lies in the MKL + OpenCV + numpy. 

This link might provide a guide to what is needed (although they seem to be trying to do the opposite -- exclude MKL and use OpenBLAS instead of vice-versa):

https://github.com/conda-forge/numpy-feedstock/issues/108

**Comment by jrmadsen** [comment]
Ok figured it out:

> scipy                          1.2.1 py27_blas_openblash1522bff_0  conda-forge         
scipy                          1.2.1  py27h09a28d5_1  conda-forge         
scipy                          1.2.1  py27h7c811a0_0  pkgs/main           
scipy                          1.2.1  py27he2b7bc3_0  pkgs/main           
scipy                          1.2.1 py36_blas_openblash1522bff_0  conda-forge         
scipy                          1.2.1  py36h09a28d5_1  conda-forge         
scipy                          1.2.1  py36h7c811a0_0  pkgs/main           
scipy                          1.2.1  py36he2b7bc3_0  pkgs/main           
scipy                          1.2.1 py37_blas_openblash1522bff_0  conda-forge         
scipy                          1.2.1  py37h09a28d5_1  conda-forge         
scipy                          1.2.1  py37h7c811a0_0  pkgs/main           
scipy                          1.2.1  py37he2b7bc3_0  pkgs/main           
scipy                          1.3.0  py36hab63836_0  conda-forge         
scipy                          1.3.0  py37hab63836_0  conda-forge         

scipy 1.3.0 in version 1.3.0 is tagged erroneously (no openblas variant) because I have 

> scipy                          1.3.0  py37hab63836_0  conda-forge

installed but the linker shows:

```shell
$ ldd /opt/packages/python/anaconda/4.5/envs/tomopy-37-mkl/lib/python3.7/site-packages/scipy/linalg/_fblas.cpython-37m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffca77c7000)
	libopenblas.so.0 => /usr/local/lib/libopenblas.so.0 (0x00007ffaa495d000)
	libgfortran.so.4 => /opt/packages/python/anaconda/4.5/envs/tomopy-37-mkl/lib/python3.7/site-packages/scipy/linalg/../../../../libgfortran.so.4 (0x00007ffaa5a16000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffaa45bf000)
	libgcc_s.so.1 => /opt/packages/python/anaconda/4.5/envs/tomopy-37-mkl/lib/python3.7/site-packages/scipy/linalg/../../../../libgcc_s.so.1 (0x00007ffaa45aa000)
	libquadmath.so.0 => /opt/packages/python/anaconda/4.5/envs/tomopy-37-mkl/lib/python3.7/site-packages/scipy/linalg/../../../../libquadmath.so.0 (0x00007ffaa4576000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffaa4185000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffaa3f66000)
	libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007ffaa3c35000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ffaa59ad000)
```

It is not failing locally because I have openblas installed in the system (`/usr/local/lib/libopenblas.so`) but Travis does not. For now, I will just specify that scipy < 1.3.0 and file an issue with the scipy feedstock.

**Comment by jrmadsen** [comment]
@carterbox Latest commit fixes this issue. Please merge the PR when it succeeds. I have just tested the GPU code and everything looks good. If you are concerned about bugs, they will not be found by the code just sitting here in a separate branch with nobody it -- the best way to find them, if they exist, is to merge into the master and let people develop against it.

**Comment by dgursoy** [comment]
+1

**Comment by jrmadsen** [comment]
Note: the TiMemory plotting is failing for Python 2.7:

https://cdash.nersc.gov/testDetails.php?test=98224&build=15583

```
 Traceback (most recent call last):
  File "/home/travis/miniconda/envs/tomopy/lib/python2.7/site-packages/timemory/plotting/plotting.py", line 1018, in plot
    plot_timing(_data, display, output_dir, echo_dart)
  File "/home/travis/miniconda/envs/tomopy/lib/python2.7/site-packages/timemory/plotting/plotting.py", line 820, in plot_timing
    's')
  File "/home/travis/miniconda/envs/tomopy/lib/python2.7/site-packages/timemory/plotting/plotting.py", line 726, in plot_generic
    dpi=plot_params.img_dpi)
  File "/home/travis/miniconda/envs/tomopy/lib/python2.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/home/travis/miniconda/envs/tomopy/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
TclError: no display name and no $DISPLAY environment variable
```

Everything is fine in 3.6 and 3.7 so it must just be a bug in matplotlib for 2.7. EOF is this year, it might be superfluous to continue testing for it.

**Comment by carterbox** [comment]
Haha. I just came to the same conclusion about `scipy`. Good job everyone.

**Comment by carterbox** [comment]
I freaked out for a minute because I merged this before I updated the version number in the files, but then I remembered that the version number is now scraped from the git tags. :smile: 

@jrmadsen Would you like to write the release summary for this version?

**Pull request merged**
