### PR TITLE
Removed h5py usage in read_als_832h5 (this is an old PR I neglected to add)

### PR DESCRIPTION
**Pull request by lbluque**
I know the exchange functions will be removed, but wanted to fix this anyway

### CODE REVIEW

**Comment by decarlof** [comment]
can you remove it from https://github.com/data-exchange/dxchange then?

**Comment by dgursoy** [comment]
Should I accept this? @decarlof @lbluque

**Comment by tomopy** [comment]
yes, since this is going away from tomopy ...
On dxchange I want  to validate on an ALS data set first before accepting a similar
pull request,
f

________________________________

**Comment by tacaswell** [comment]
Sorry to show up late in a PR with peanut-gallery comments, but it is best if you use h5py files in a context manager

```python
with h5py.File(fname) as f:
    # ...
    pass
```

Which ensures the files get closed (if they do not it can lead to weird bugs).

**Comment by decarlof** [comment]
@tacaswell good suggestion I will implement this under dxchange

**Pull request merged**
