### PR TITLE
BLD: Update PTL submodule with libatomic build fixes for riscv64

### PR DESCRIPTION
**Pull request by LocutusOfBorg**
Enables building the accel module with OpenCV on RISCV64 by adding a patch which adds libatomic.

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
I can say that my two commits are good, there are two additional warnings fixes on tomopy branch, please check them if possible :)

**Comment by carterbox** [comment]
Build failed for MacOS. I rolled back the PTL submodule to before your changes to see if the cause of the failure is your changes or the two commits before that.

**Comment by LocutusOfBorg** [comment]
An additional fix on PTL worked for MACOSX

**Comment by LocutusOfBorg** [comment]
https://dev.azure.com/tomopy/tomopy/_build/results?buildId=1930&view=logs&j=25205f61-0083-568f-d89e-fccb058f0be2&t=e0a5e1dc-ca20-5e5d-f2dc-351ab9f2b368

**Comment by LocutusOfBorg** [comment]
https://github.com/jrmadsen/PTL/pull/43 this is the fix

**Review by carterbox — APPROVED** [review]

**Comment by carterbox** [comment]
@LocutusOfBorg, thanks for your contribution. This PR has motivated me to update PTL to the latest version instead of maintaining a special version as a submodule, so keep an eye out for that. I will try to port your patches to the v2 branch of PTL, but I may need some help.

In the meantime, I hope merging this patch allows you to build the TomoPy features that you want on RISCV.

**Comment by LocutusOfBorg** [comment]
thanks! it does!

**Comment by LocutusOfBorg** [comment]
please let me know once you have a new release out, and I'll report back in case of failures :D

**Pull request merged**
